version: "3.0"
services:
  compass-env:
    image: qiangzibro/compass:latest
    volumes:
        - .:/workspace
    tty: true
    ports:
      - "8888:8888"
      - "220:22"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    entrypoint: sh -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/workspace --allow-root --NotebookApp.token=''"
